### ISSUE TITLE
[feat] Change default Scale in Instant to UTC when printing to stdout

### ISSUE THREAD

**Issue by vishwa2710** [open-space-collective/open-space-toolkit-physics#240]
**Is your feature request related to a problem? Please describe.**
Currently, in the Instant class we print to stdout with the TT Scale, which while appropriate, can be confusing to users, when they've inputted it in a different frame.

**Describe the solution you'd like**
We should log in UTC as that is the most widely used.

**Describe alternatives you've considered**
Alternatively, we can track the Scale the instant was created with and log in that scale.

**Comment by kyle-cochran** [comment]
Fixed, we now have:
![Screenshot 2024-05-17 at 11 15 11 AM](https://github.com/open-space-collective/open-space-toolkit-physics/assets/16886766/b93d3b00-cf3e-4224-9526-1283e7e401f8)
