### ISSUE TITLE
SPICE Download manager fails [Python]

### ISSUE THREAD

**Issue by addy999** [open-space-collective/open-space-toolkit-physics#26]
Setting SPICE, IERS, and EARTH managers to "Automatic" throws an error on epehm downloads when creating a new Environment.:

```python
os.environ["LIBRARY_PHYSICS_COORDINATE_FRAME_PROVIDERS_IERS_MANAGER_MODE"] = "Automatic"
os.environ["LIBRARY_PHYSICS_ENVIRONMENT_EPHEMERIDES_SPICE_ENGINE_MODE"] = "Automatic"
os.environ["LIBRARY_PHYSICS_ENVIRONMENT_GRAVITATIONAL_EARTH_MANAGER_ENABLED"] = "true"
```

![image](https://user-images.githubusercontent.com/15189112/62503582-ce0ce200-b7c2-11e9-9afe-a825ec3226c5.png)

The same error is thrown even if given a path to empty folders: 
```python
os.environ["LIBRARY_PHYSICS_ENVIRONMENT_EPHEMERIDES_SPICE_MANAGER_LOCAL_REPOSITORY"] = "./library/spice"
os.environ["LIBRARY_PHYSICS_COORDINATE_FRAME_PROVIDERS_IERS_MANAGER_LOCAL_REPOSITORY"] = "./library/iers"
os.environ["LIBRARY_PHYSICS_ENVIRONMENT_GRAVITATIONAL_EARTH_MANAGER_LOCAL_REPOSITORY"] = "./library/earth"
```
![image](https://user-images.githubusercontent.com/15189112/62503727-7327ba80-b7c3-11e9-9149-5be227674af1.png)

**Comment by kyle-cochran** [comment]
I don't know when exactly this was fixed, but it's no longer the case. The managers seem to be working now! Closing this out.
