### ISSUE TITLE
Instant.getDateTime(Scale.UTC) gives a Segmentation fault

### ISSUE THREAD

**Issue by addy999** [open-space-collective/open-space-toolkit-physics#27]

**Comment by lucas-bremond** [comment]
Can you add a code snippet!

**Comment by addy999** [comment]
![image](https://user-images.githubusercontent.com/15189112/63461319-60012580-c426-11e9-9fa1-dcb895833b6a.png)

**Comment by lucas-bremond** [comment]
I believe this is now fixed. Please re-open if this issue persists.
