### ISSUE TITLE
Fails to import celestial bodies except Earth [Python]

### ISSUE THREAD

**Issue by robinpdm** [open-space-collective/open-space-toolkit-physics#48]
In Python, trying to import celestial bodies other than `Earth` seems to fail:

![error_1](https://user-images.githubusercontent.com/38868300/83481463-b5a53c80-a452-11ea-9ec2-a124adf8b2a5.png)

Indeed, neither `Moon` nor `Sun` shows up in the list of attributes:

![error_2](https://user-images.githubusercontent.com/38868300/83481637-2e0bfd80-a453-11ea-9ffb-a0187725f37f.png)

**Comment by lucas-bremond** [comment]
Good catch!

Indeed, other celestial bodies are available here (C++ side):

https://github.com/open-space-collective/open-space-toolkit-physics/tree/master/src/OpenSpaceToolkit/Physics/Environment/Objects/CelestialBodies

But Python mapping is missing:

https://github.com/open-space-collective/open-space-toolkit-physics/tree/master/bindings/python/src/OpenSpaceToolkitPhysicsPy/Environment/Objects/CelestialBodies

Can you create a PR?
